#define CHORDAL_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 25

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 20

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 35

#define SERIAL_NUMBER "qvWx4/3vVNgB"
#define LAYER_STATE_8BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60




#define MOUSEKEY_INERTIA

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 150

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 32

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 32

#define MOUSEKEY_FRICTION 24
#define MOUSEKEY_MOVE_DELTA 1
